### PR TITLE
Filter alternatives

### PR DESCRIPTION
**Pull request by ibaca**
screen shot 2014-11-20 at 21 58 31

### CODE REVIEW

**Comment by ibaca** [comment]
The sizzle.match option looks promising, what do you think? The filter code with this option is quite simple.

```
public GQuery filter(String selector) {
  JsArray<Element> seed = JavaScriptObject.createArray().cast();
  for (Element element : elements()) seed.push(element);
  return pushStack(SelectorEngineSizzle.matches(selector, seed).<JsNodeArray>cast(), "filter", selector);
}
```

The problem is that the sizzle code is a bit old and some selectors test fails like $("p").is(":hidden").

Also, the 'matches' operator might be added to the Selector interface (I didn't investigate if other engines support 'matches') so other engines which support 'matches' might use its own implementation, and fallback to sizzle if is not supported.

**Comment by manolo** [comment]
Yep, but forcing to include Sizzle to any gquery project is not a good idea. Maybe investigate what is doing Sizzle and try to emulate it in java, or jsni, but Sizzle code is quite obscure, I don't have the time to study it right now, so if you can take a look a figure out how they do.
Also I have test jQuery and filter seems not work with detached nodes, so probably that is the reason why it performs so good.
I have updated my patch so as we have a filter implementation like jQuery, but and extra method signature for enabling ghost, can you check your code with that?

**Comment by ibaca** [comment]
screen shot 2014-11-22 at 13 17 44

Your patch improve the performance but IMO the performance is not enough to use $live events the body, which is why I am interested in this performance problem :wink:.

To show this $live situation, I have added some tools in the Test so you can see easy. I add a algorithm selector to choose each filter strategy, so if you change the strategy and move the mouse over the table you can "feel" the problem.

I had to merge your MGQuery with GQuery, so now all filters are in a local copy of GQuery (a bit ugly). But I need that to test the new filters methods through the $live>is() calls.

Finally the breadcrumb which appears when you change the algorithm show the performance of every $is in the element hierarchy (which is what filtered event do for each processed event). An interesting result I see with this breadcrumb is that both new filters spent a minimum of ~30ms on each element, which is very suspicious because test something like $("some div element with 1 child and 1 parent").is("something") must be instantaneous.

**Comment by ibaca** [comment]
The filter_default performance looks worst in the options filter case, but it's much better in the $live case.

Running filter method on +/- 500 elements with GQuery default: 70ms
Running filter method on +/- 500 elements with GQuery new (considerDetached=false): 15ms
Running filter method on +/- 500 elements with GQuery predicate: 4ms

Breadcrumb for default, new_false and predicate filters

```
filterDefault:   DIV  0ms > TD  0ms > TR  3ms > TBODY  8ms > TABLE  3ms > DIV  3ms > DIV  2ms > DIV  3ms > DIV  3ms > total 25ms
filterNewFalse:  DIV 48ms > TD 35ms > TR 37ms > TBODY 36ms > TABLE 36ms > DIV 35ms > DIV 36ms > DIV 35ms > DIV 39ms > total 337ms
filterPredicate: DIV  1ms > TD  0ms > TR  0ms > TBODY  0ms > TABLE  0ms > DIV  0ms > DIV  0ms > DIV  0ms > DIV  0ms > total  1ms
```

**Comment by ibaca** [comment]
New filter implementation https://github.com/manolo/gquery/commit/28c935fd3e83d13da18a7fc80866e3ef8ce15285

Running filter method on +/- 500 elements with GQuery default: 74ms
Running filter method on +/- 500 elements with GQuery old: 621ms
Running filter method on +/- 500 elements with GQuery new (considerDetached=false): 3ms
Running filter method on +/- 500 elements with GQuery new (considerDetached=true): 3ms
Running filter method on +/- 500 elements with GQuery predicate: 4ms

Breadcrumb

```
filterDefault: DIV 0ms > TD 0ms > TR 3ms > TBODY 3ms > TABLE 8ms > DIV 3ms > DIV 2ms > DIV 2ms > DIV 3ms > total 24ms
filterDetachedFalse: DIV 4ms > TD 5ms > TR 8ms > TBODY 16ms > TABLE 5ms > DIV 5ms > DIV 3ms > DIV 5ms > DIV 5ms > total 56ms
filterDetachedTrue: DIV 0ms > TD 0ms > TR 4ms > TBODY 3ms > TABLE 3ms > DIV 3ms > DIV 3ms > DIV 3ms > DIV 3ms > total 22ms
filterPredicate: DIV 0ms > TD 0ms > TR 0ms > TBODY 0ms > TABLE 0ms > DIV 0ms > DIV 0ms > DIV 0ms > DIV 0ms > total 0ms
```

**Pull request closed without merging**
